### ISSUE TITLE
Missing Manager after updating to Comfyui 0.4.0.

### ISSUE THREAD

**Issue by tonywhite11** [comfyanonymous/ComfyUI#11222]
I can't find the manager. Is it somewhere new because I reinstalled and I still don't see it.

**Comment by salmons1201** [comment]
I'm in the same situation.

**Comment by pazzuzu** [comment]
Comfyui developers are so smart that they surpass themselves with every update. Therefore, don't bother trying to fix it. Neither the manager will work nor will you be able to see the extra model links. You will have to reinstall everything from scratch and try dozens of combinations. I reinstalled it from scratch, but the manager is still not visible.

**Comment by Cunningcory** [comment]
I can see my Manager, but nothing works anymore. I get:

Loading aborted due to error reloading workflow data
TypeError: this.widgets.values(...).filter is not a function

Looks like v0.4.0 broke everything.

**Comment by benceruleanlu** [comment]
The manager has moved to the Comfy menu here

<img width="474" height="1050" alt="Image" src="https://github.com/user-attachments/assets/d5034816-1f4a-46f1-81cd-c7661351e879" />

**Comment by salmons1201** [comment]
@benceruleanlu you're genius

**Comment by pazzuzu** [comment]
If you're experiencing model and custom node issues after the update, you can try the following method. I was able to get the old nodes and models working like this. First, I backed up my old settings and old comfyui folder under a different name. I deleted the current comfyui. I downloaded the latest comfyui desktop program. I performed a clean installation. I deleted the second comfyui data files that were created. I renamed the old comfyui folder back to its original name. I know this sounds a bit confusing, but if you've been using comfyui for a long time, you'll understand what I mean. Everything is working now.

**Comment by Cunningcory** [comment]
> I can see my Manager, but nothing works anymore. I get:
> 
> Loading aborted due to error reloading workflow data TypeError: this.widgets.values(...).filter is not a function
> 
> Looks like v0.4.0 broke everything.

My issue ended up being fix by updating Pinokio to the latest version (for those who find themselves here with a similar issue). Pinokio's browser needed to be updated to work correctly with v0.4.0.
