### ISSUE TITLE
AttributeError: '_v_block' on ROCm — CUDA-graph prefetch path enabled by is_device_cuda() even though comfy_aimdo graph capture isn't ROCm-functional

### ISSUE THREAD

**Issue by boxwrench** [comfyanonymous/ComfyUI#15594]
## Repro

Run any workflow that hits `comfy/model_prefetch.py`'s `prefetch_queue_pop()` graph-capture branch on an AMD/ROCm GPU. I hit this via the new **MiniMax Music 3** support (`RVQDepthDecoder`), but the gating logic in `prefetch_queue_pop` isn't Music3-specific, so this likely affects any model path that goes through it on ROCm.

## Environment

- ROCm 7.2.1
- AMD Radeon AI PRO R9700 (gfx1201)
- torch 2.9.1+rocm7.2.1
- ComfyUI v0.33.0 (commit `2f35f4a`)

## Error

```
AttributeError: 'RVQDepthDecoder' object has no attribute '_v_block'
  File "comfy/model_prefetch.py", line 116, in prefetch_queue_pop
    signature = comfy_aimdo.model_vbar.vbar_fault(module._v_block)
  File "comfy/ldm/minimax_music/ar.py", line 320, in generate
    comfy.model_prefetch.prefetch_queue_pop(...)
```

## Cause

```python
enable_graph = enable_graph and not args.disable_cuda_graphs and comfy.model_management.is_device_cuda(device)
```

`is_device_cuda()` returns `True` for ROCm's HIP-as-CUDA device type, but `comfy_aimdo.model_vbar`'s CUDA graph capture/replay doesn't appear to be functional on ROCm — the module ends up in a state where `_comfy_graph` exists but `_v_block` was never actually set, and the next call reads `module._v_block` unconditionally instead of checking for it first.

## Workaround

`--disable-cuda-graphs` launch flag avoids the crash entirely; generation then runs correctly (tested full MiniMax Music 3 text-to-music generation end to end after adding the flag).

## Suggested fix

Gate `enable_graph` on real CUDA-graph capability (e.g. checking `torch.version.hip is None`, or a dedicated capability probe) rather than the generic `is_device_cuda()` shim check — or have `comfy_aimdo`/the prefetch path degrade gracefully (skip graph capture) instead of raising `AttributeError` when the graph state is incomplete.

This was introduced in #15570 ("Implement Minimax Music 3 + Core Support for Cuda Graphs").

**Comment by boxwrench** [comment]
Correcting my own diagnosis here — this is already fixed by 03fa4e4 ("Fix minimax music not working on non dynamic vram", #15588), merged shortly before I filed this. The actual root cause wasn't the ROCm `is_device_cuda()` shim gating as I guessed, but that `_v_block` is never set on the module when `--disable-dynamic-vram` is used (which is how I was running), and the old code read `module._v_block` unconditionally. The fix adds a `getattr(module, "_v_block", None) is not None` guard, which resolves it regardless of device/backend.

Closing as already fixed — thanks for the fast turnaround.
