### ISSUE TITLE
Regression: MiniMax‑H3 works perfectly on 0.34.2, `HostBuffer.read_file_slice` CUDA OOM on versions >=0.34.3 with identical workflow & weights

### ISSUE THREAD

**Issue by foreveralive1** [comfyanonymous/ComfyUI#16138]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

Provide a reliable way to fully disable the on‑demand weight streaming fallback to the old full‑weight upload behaviour (the 0.34.2 loading logic).
Current switches cannot turn off this feature completely for large LLM‑style text encoders such as MiniMax‑H3.

### Environment

- OS: Windows 11
- GPU: RTX 5080 Laptop
- Driver: Latest Studio / Game‑Ready driver
- ComfyUI version: Broken ≥0.34.3, Stable = 0.34.2
- Model: MiniMax‑H3 audio text‑encoder (same weight file used in both versions)

### Problem description

The exact same workflow and model weight run **without any error on 0.34.2**.
After upgrading to any release newer than 0.34.2, generation crashes consistently during the text‑encoding step of MiniMax‑H3.

### Steps to Reproduce

Run and oom at the first Conditioning

[【WorkFisher】全网最强！MINIMAX文戏工作流！！！！.json](https://github.com/user-attachments/files/31874575/WorkFisher.MINIMAX.json)

### Debug Logs

```powershell
aimdo: src/hostbuf.c:283:ERROR:hostbuf_read_file_slice: device copy failed result=2
RuntimeError: HostBuffer.read_file_slice failed
CUDA error: out of memory
Call stack goes through cast_modules_with_vbar → read_tensor_file_slice_into
```
