### ISSUE TITLE
GroupNodeHandler. getGroupData is not a function

### ISSUE THREAD

**Issue by ziyaxuanyi** [comfyanonymous/ComfyUI#15116]
When I upgraded comfyui-background-package to 1.47.10, clicking run, the browser will pop up an error message "GroupNodeHandler. getGroupData is not a function", and the workflow cannot be run.

The old version of comfyui-background-package runs well.

How should I solve it？

**Comment by doogyhatts** [comment]
I am using other workflows but also have the same problem.

**Comment by signalstop** [comment]
GroupNodeHandler.getGroupData is not a function.

I can't use any workflow. I went all the way back to v0.28.2

Something in latest update seemed to permanently cause "GroupNodeHandler.getGroupData is not a function" when trying to run any workflow with no visible errors in the workflow.

**Comment by signalstop** [comment]
> When I upgraded comfyui-background-package to 1.47.10, clicking run, the browser will pop up an error message "GroupNodeHandler. getGroupData is not a function", and the workflow cannot be run.
> 
> The old version of comfyui-background-package runs well.
> 
> How should I solve it？

which version is working for you? And do you mean: comfyui-frontend-package version: 1.47.10?  I'm going to try and revert back to an old package.

**Comment by signalstop** [comment]
It seems to be just the actual RUN button that's the issue.   I can put this node, not connected to anything and hit "send" and the workflow will run.

<img width="532" height="337" alt="Image" src="https://github.com/user-attachments/assets/5969c964-e751-42f0-a78b-6a46ad377af6" />

That node comes from here: (if need a temporary workaround)

https://github.com/no8d/ComfyUI-NO8D-controls/

**Comment by doogyhatts** [comment]
I tried adding the node but I am still getting the error.

I will run my workflows on runninghub for the time being, until this is fixed.

**Comment by signalstop** [comment]
> I tried adding the node but I am still getting the error.
> 
> I will run my workflows on runninghub for the time being, until this is fixed.

Did you click the "send" button to try and run the workflow?  The Run button still doesn't work for me but the "Send" bypasses the RUN button and executes the workflow.

**Comment by ziyaxuanyi** [comment]
I have found the reason, which is due to the submission modification of the comfyui-frontend-package library: [https://github.com/Comfy-Org/ComfyUI_frontend/pull/12347](url)  It removed the relevant methods, which some extension custom_nodes rely on, resulting in errors

Provide two solutions:
1. Roll back the comfyui-frontend-package version to 1.46.1, which is the last version that has not yet undergone removal and modification operations. Everything will work properly, but this also means that you will never be able to update the comfyui-frontend-package, and you may miss out on future new features of Comfyui
2. We need to check which custom_nodes you have installed have called this method. This may be a bit troublesome, perhaps you can use AI to help you quickly check (which is how I did it). Once you find out which custom_nodes called the method, please update these custom_nodes to the latest version. If the problem still persists after the update, please contact the custom_nodes author for repair, or disable these custom_nodes directly

For me, the cg use everywhere custom_nodes caused my problem. When I updated the custom_nodes to the latest version, everything worked properly, and it was clear that the custom_nodes author had fixed the issue.

**Comment by doogyhatts** [comment]
Ok I managed to get it to work using the NO8D-prompt-view node.

**Comment by signalstop** [comment]
> I have found the reason, which is due to the submission modification of the comfyui-frontend-package library: [https://github.com/Comfy-Org/ComfyUI_frontend/pull/12347](url) It removed the relevant methods, which some extension custom_nodes rely on, resulting in errors
> 
> Provide two solutions:
> 
>     1. Roll back the comfyui-frontend-package version to 1.46.1, which is the last version that has not yet undergone removal and modification operations. Everything will work properly, but this also means that you will never be able to update the comfyui-frontend-package, and you may miss out on future new features of Comfyui
> 
>     2. We need to check which custom_nodes you have installed have called this method. This may be a bit troublesome, perhaps you can use AI to help you quickly check (which is how I did it). Once you find out which custom_nodes called the method, please update these custom_nodes to the latest version. If the problem still persists after the update, please contact the custom_nodes author for repair, or disable these custom_nodes directly
> 
> 
> For me, the cg use everywhere custom_nodes caused my problem. When I updated the custom_nodes to the latest version, everything worked properly, and it was clear that the custom_nodes author had fixed the issue.

Thanks. that same cg-use-everywhere node was causing my issues as well. updated the node and RUN works again.

**Comment by hicaonmb** [comment]
I have many custom nodes，how to find which custom node needs to update?

**Comment by ziyaxuanyi** [comment]
> I have many custom nodes，how to find which custom node needs to update?

Maybe you can use AI to help you.

**Comment by dimmedcrow** [comment]
In my case by debugging I found problem node was "cg-use-everywhere"

**Comment by komikndr** [comment]
@dimmedcrow thanks, i upgraded the CG Use Everywhere and it fix the issue
