### ISSUE TITLE
[Critical Dependency Conflict] Massive Node Failures on Python 3.12 + Windows (Protobuf vs TensorFlow vs Transformers)

### ISSUE THREAD

**Issue by wzgrx** [comfyanonymous/ComfyUI#12198]
### Feature Idea

Body / 内容
System Environment:

OS: Windows 11

GPU: NVIDIA GeForce RTX 5090 Laptop GPU

Python: 3.12.10

ComfyUI Version: v0.11.1

Torch Version: 2.10.0+cu130

Summary: I am reporting a severe environment conflict affecting over 30 custom nodes on a fresh ComfyUI installation using Python 3.12. The console is flooded with ImportError crashes.

The root cause is a "Dependency Hell" scenario involving TensorFlow, Transformers, and Protobuf. Specifically, transformers (used by many nodes) attempts to import tensorflow if present, which then crashes due to a version mismatch with google.protobuf.

Impact Report: Broken Nodes List

Based on the startup logs, the following nodes are completely non-functional:

1. Victims of the "Protobuf/TensorFlow" Conflict (ImportError: runtime_version): These nodes fail because transformers or diffusers triggers a crash in tensorflow dependencies.

ComfyUI-nunchaku (and all sub-nodes: Flux, Qwen, PuLID)

Boyonodes

ComfyUI-Florence2

ComfyUI-Qwen-VL & zhihui_nodes_comfyui (Qwen3VL)

ComfyUI-ReActor (InsightFace/ONNX protobuf conflict)

ComfyUI-RMBG (v3.0)

ComfyUI-SAM2

ComfyUI-TeaCache

ComfyUI-SUPIR

ComfyUI-CogVideoXWrapper & VideoX-Fun

ComfyUI-HunyuanVideo-Foley

ComfyUI-LTXVideo

ComfyUI-mnemic-nodes

ComfyUI-SeedVR2_VideoUpscaler

was-node-suite-comfyui (BLIP models)

ComfyUI_InstantID

PiePieTweaks

comfyui-vrgamedevgirl

2. Python 3.12 Compatibility & Missing Dependencies:

ComfyUI-SDPose-OOD: Fails to install mmcv (needs mim which fails on Py3.12 due to pkgutil.ImpImporter removal).

ComfyUI-FlashVSR: Incompatible with transformers >= 5.0.0.

ComfyUI-translate-offline: Missing optimum / onnxruntime.

ComfyUI_LayerStyle: opencv-python vs opencv-contrib-python conflict.

Detailed Error Logs

Error Type A: The Protobuf Crash (Most Common)

Plaintext
File "...\venv\Lib\site-packages\transformers\image_transforms.py", line 48, in <module>
    import tensorflow as tf
File "...\venv\Lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 9, in <module>
    from google.protobuf import runtime_version as _runtime_version
ImportError: cannot import name 'runtime_version' from 'google.protobuf'
Error Type B: Python 3.12 Removal of ImpImporter (Affecting MMCV/MIM)

Plaintext
File "...\pkg_resources\__init__.py", line 2172, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
Actions Taken

Uninstalling TensorFlow: This resolves the Protobuf conflict for transformers-based nodes, but breaks nodes that explicitly require TF.

Upgrading Protobuf: pip install protobuf --upgrade fixes some nodes but breaks others that pin older versions (like ReActor/ONNX).

Forcing Setuptools Upgrade: pip install setuptools wheel --upgrade allows mim to work on Py3.12, but this is a manual fix most users miss.

Request: The current dependency management for ComfyUI custom nodes is extremely fragile on Python 3.12.

Can we have a "Safe Mode" or strictly enforced guideline to prevent nodes from installing TensorFlow unless absolutely critical? It is the primary source of instability in this PyTorch ecosystem.

Please update the default requirements to ensure protobuf, onnxruntime, and transformers are compatible out-of-the-box for common nodes like Florence2 and SAM2.

**Comment by kajan988** [comment]
++++
