### ISSUE TITLE
What should I do if the Python 3.12 in the portable package is incompatible with some plugins?

### ISSUE THREAD

**Issue by Sdreamtale** [comfyanonymous/ComfyUI#7512]
I installed this plugin: https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet. However, the node ArgosTranslateNode encountered an issue, showing the error message "module 'pkgutil' has no attribute 'ImpImporter'". The solution provided by the author of this plugin doesn't work for me. How can I make Python 3.12 compatible with this plugin?
This is the link of the question that was asked in the Issues plugin.
https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/130

**Comment by woct0rdho** [comment]
This should work with Python 3.12 . However, you need to upgrade pip and setuptools:

First cd to the folder `python_embeded` if you use it (if you use the default bat file to start ComfyUI)

Then run:
```
.\python.exe -m ensurepip -U
.\python.exe -m pip install -U pip
.\python.exe -m pip install -U setuptools
```

**Comment by Sdreamtale** [comment]
When I run the command "\python.exe -m ensurepip -U" in the terminal of the python_embeded folder, it prompts "python.exe: No module named ensurepip".

**Comment by woct0rdho** [comment]
Ok it seems ensurepip is not in the embeded Python. But pip should be there and you can continue to run the next commands

**Comment by Sdreamtale** [comment]
Thank you very much. You have solved the problem that has troubled me for a long time.
