### PR TITLE
xlabs Flux controlnet implementation.

### PR DESCRIPTION
**Pull request by comfyanonymous**
I'm leaving this here because I'm not sure if I implemented it correctly or if the results are supposed to be this bad.

It only seems to work with FluxGuidance set to 4.0

Here's a workflow for anyone who wants to test it:

ComfyUI_170971_

You can find the model file here: https://huggingface.co/XLabs-AI/flux-controlnet-canny/tree/main

### CODE REVIEW

**Comment by gradient-diffusion** [comment]
we trained it with only gs 4 and tomorrow you will se better version

**Comment by huchenlei** [comment]
Playwright test failed for missing `from __future__ import annotations`.

**Comment by starinskycc** [comment]
https://huggingface.co/xinsir/controlnet-union-sdxl-1.0
Can we train a versatile ControlNET like this expert?

**Comment by boogieLing** [comment]
The following error is encountered when running to ControlNetLoader when trying to load CN.
I'm using the above workflow and I don't know what I'm doing wrong, ask for help please.....

`Error occurred when executing ControlNetLoader:

'NoneType' object has no attribute 'keys'

File "/root/ComfyUI/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/root/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/root/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/root/ComfyUI/nodes.py", line 720, in load_controlnet
controlnet = comfy.controlnet.load_controlnet(controlnet_path)
File "/root/ComfyUI/comfy/controlnet.py", line 433, in load_controlnet
return load_controlnet_mmdit(controlnet_data)
File "/root/ComfyUI/comfy/controlnet.py", line 343, in load_controlnet_mmdit
model_config = comfy.model_detection.model_config_from_unet(new_sd, "", True)
File "/root/ComfyUI/comfy/model_detection.py", line 284, in model_config_from_unet
unet_config = detect_unet_config(state_dict, unet_key_prefix)
File "/root/ComfyUI/comfy/model_detection.py", line 37, in detect_unet_config
state_dict_keys = list(state_dict.keys())`

**Comment by meimeilook** [comment]
It works on controlnet weight 0.9 above, just works. waiting for better quality.

CN
no-CN

**Comment by ivanoff13** [comment]
Снимок

**Comment by sunyiwk** [comment]
> Снимок

I have the same problem

**Comment by oumad** [comment]
The instantX version seems to have a more permissive license : https://huggingface.co/InstantX/FLUX.1-dev-Controlnet-Canny-alpha
Would the same implementation work for it too ?

**Comment by JorgeR81** [comment]
InstantX is so large ( 7 GB ) in comparison with XLabs-AI  ( 1.5GB ).
It may nor work for lower end systems that can currently run Flux. 
I hope we can get good controlnet quality without need for these sizes.

**Comment by doggeddalle** [comment]
> The instantX version seems to have a more permissive license : https://huggingface.co/InstantX/FLUX.1-dev-Controlnet-Canny-alpha Would the same implementation work for it too ?

thanks for linking these so we know about them. browsing internet feels like fugue state these days

**Comment by JorgeR81** [comment]
> It works on controlnet weight 0.9 above, just works. waiting for better quality.

The pose seems good, but it seems it got more of an illustration style, with the ControlNet.

@meimeilook Can you try adding their realism lora ?

https://huggingface.co/XLabs-AI/flux-RealismLora

**Comment by kaykay-drills** [comment]
Tried to pull this branch locally and I still get the error reported above :(
```
Error occurred when executing ControlNetLoader:

'NoneType' object has no attribute 'keys'
```

Will this one be merged tomorrow or in the upcoming week(s)?

**Comment by doggeddalle** [comment]
> Tried to pull this branch locally and I still get the error reported above :(
> 
> ```
> Error occurred when executing ControlNetLoader:
> 
> 'NoneType' object has no attribute 'keys'
> ```
> 
> Will this one be merged tomorrow or in the upcoming week(s)?

gonna assume its borked

**Comment by nikolaiusa** [comment]
git checkout xlabs_flux_controlnet

**Comment by kaykay-drills** [comment]
> git checkout xlabs_flux_controlnet

yes, first thing I did was to checkout this branch :)
still doesn't work :(

**Comment by ZiBrianQian** [comment]
> > git checkout xlabs_flux_controlnet
> 
> yes, first thing I did was to checkout this branch :) still doesn't work :(
> 
> ```
> F:\Projects\AI\COMFY-UI\ComfyUI_windows_portable\ComfyUI\ComfyUI>git branch
> * xlabs_flux_controlnet
> ```
> 
> ```
> !!! Exception during processing!!! 'NoneType' object has no attribute 'keys'
> ```

Update ComfyUI. then run the git checkout xlabs_flux_controlnet again. It worked for m.

**Comment by Bortus-AI** [comment]
> > > git checkout xlabs_flux_controlnet
> > 
> > 
> > yes, first thing I did was to checkout this branch :) still doesn't work :(
> > ```
> > F:\Projects\AI\COMFY-UI\ComfyUI_windows_portable\ComfyUI\ComfyUI>git branch
> > * xlabs_flux_controlnet
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > !!! Exception during processing!!! 'NoneType' object has no attribute 'keys'
> > ```
> 
> Update ComfyUI. then run the git checkout xlabs_flux_controlnet again. It worked for m.

that worked!

**Review by Bortus-AI — APPROVED** [review]

**Comment by WingeD123** [comment]
> InstantX is so large ( 7 GB ) in comparison with XLabs-AI ( 1.5 GB ) ! It may not work for lower end systems which can currently run Flux. I hope we can get good controlnet quality without the need for these sizes.

InstantX just replaced the 7g one with a 3.3g version

**Comment by kaykay-drills** [comment]
```
F:\Projects\AI\COMFY-UI\ComfyUI_windows_portable\ComfyUI\ComfyUI>git branch
xlabs_flux_controlnet
```
New error spotted:
```
'NoneType' object has no attribute 'lower'
```

**Comment by ZiBrianQian** [comment]
> ```
> F:\Projects\AI\COMFY-UI\ComfyUI_windows_portable\ComfyUI\ComfyUI>git branch
> xlabs_flux_controlnet
> ```
> 
> New error spotted:
> 
> ```
> 'NoneType' object has no attribute 'lower'
> ```
> 
> Quick update: I tried to merge master locally into this branch as well but no luck

Had the same proble, with XLabs Flux_dev_fp8. Try this model instead https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors

**Comment by kaykay-drills** [comment]
> Had the same problem, with XLabs Flux_dev_fp8. Try this model instead https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors

Now the error is on the `SampleCustomAdvanced`

`TypeError: ControlNetFlux.forward() missing 1 required positional argument: 'y'`

**Comment by 93041025** [comment]
> Снимок

same issue. i have tried the safetensors(by comfy.org) and sft(original) but same issues.

**Comment by 93041025** [comment]
> The instantX version ~seems to have a more permissive license~ : https://huggingface.co/InstantX/FLUX.1-dev-Controlnet-Canny-alpha Would the same implementation work for it too ?

it generates another error "Error occurred when executing ControlNetLoader:

'pos_embed.proj.weight'"

**Comment by djdookie** [comment]
After some testing I can say this branch + controlnet works great for me even on 1024x1024.
Thanks for the quick implementation.

**Comment by BaNZaY777666** [comment]
i have slightly different problem(

Error occurred when executing ControlNetLoader:

'pos_embed.proj.weight'

File "C:\AI\Matrix\Packages\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\AI\Matrix\Packages\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\AI\Matrix\Packages\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\AI\Matrix\Packages\ComfyUI\nodes.py", line 720, in load_controlnet
controlnet = comfy.controlnet.load_controlnet(controlnet_path)
File "C:\AI\Matrix\Packages\ComfyUI\comfy\controlnet.py", line 491, in load_controlnet
return load_controlnet_mmdit(controlnet_data)
File "C:\AI\Matrix\Packages\ComfyUI\comfy\controlnet.py", line 404, in load_controlnet_mmdit
new_sd = comfy.model_detection.convert_diffusers_mmdit(sd, "")
File "C:\AI\Matrix\Packages\ComfyUI\comfy\model_detection.py", line 500, in convert_diffusers_mmdit
depth = state_dict["pos_embed.proj.weight"].shape[0] // 64

**Comment by kaykay-drills** [comment]
> 'pos_embed.proj.weight'

this is because you are using the The instantX version. This branch covers xlabs controlnet model only, I believe.

**Comment by BaNZaY777666** [comment]
> > 'pos_embed.proj.weight'
> 
> this is because you are using the The InstantX version. This branch covers xlabs controlnet model only, I believe.

Indeed. But xlabs controlnet not doing well. Or I am doing something wrong?
workflow (1)

**Comment by kaykay-drills** [comment]
> > this is because you are using the The InstantX version. This branch covers xlabs controlnet model only, I believe.

Please refer to this  comment, it solved my issue.

> > Had the same problem, with XLabs Flux_dev_fp8. Try this model instead https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors

**Comment by BaNZaY777666** [comment]
> > Indeed. But xlabs controlnet not doing well. Or I am doing something wrong?
> 
> Please refer to this comment, it solved my issue.
> 
> > > Had the same problem, with XLabs Flux_dev_fp8. Try this model instead https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors

Still kinda bad

workflow (2)

**Comment by kaykay-drills** [comment]
> Still kinda bad
let's be positive! it works!

Also, try to use the nodes provided in the image proposed. at the very top.

**Comment by kaykay-drills** [comment]
It works! Thanks for the help!

A few points:
- Lora `flux_realism_lora` work can work along with Flux CNet 
- SplitSigma node is not supported
- ClipTextEncodeFlux is also not supported (that was my issue)
- applying this CNet renders weird lines to the output image with CFG 3.5 tho Shine with CFG4 

Kacey at the beach

**Comment by BaNZaY777666** [comment]
Guidance is vary important. Best value is 4.0
Best resolution is 512x512

workflow (5)

**Comment by ZiBrianQian** [comment]
> Guidance is vary important. Best value is 4.0 Best resolution is 512x512 But still noisy
> 
> workflow (5)

Try to use this workflow  https://github.com/camenduru/comfyui-colab/blob/main/workflow/flux_1_dev-xlabsai_realism_lora_compare.json

**Comment by kaykay-drills** [comment]
A few Notes

Seed 688106326432651

Cnet 0.76 head facing the camera , still nice image
Cnet 0.77 pulls up her head, still nice image
Cnet 78 the cnet kick in violently and fuck up her arms

Lora:
Keep it low, it's very strong

wf-canny-2024-08-09 181209

workflow file: [kacey-traxler-flux1-dev-fp8-cnet-canny-v1.0-workflow](https://drive.google.com/file/d/1TEfnhdc74yokJiHmW0PYK2aCVJPxq1EJ/view?usp=drive_link)

**Comment by heinrichI** [comment]
I have error:
Error occurred when executing SamplerCustomAdvanced:

 Error while processing rearrange-reduction pattern "b c (h ph) (w pw) -> b (h w) (c ph pw)".
 Input tensor shape: torch.Size([1, 16, 196, 147]). Additional info: {'ph': 2, 'pw': 2}.
 Shape mismatch, can't divide axis of length 147 in chunks of 2

  File "i:\flux\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\flux\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\flux\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\flux\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_custom_sampler.py", line 612, in sample
    samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\flux\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\flux\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\flux\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\flux\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "i:\flux\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\sampling.py", line 143, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\flux\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\flux\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 682, in __call__
    return self.predict_noise(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\flux\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\flux\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\flux\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 202, in calc_cond_batch
    c['control'] = control.get_control(input_x, timestep_, c, len(cond_or_uncond))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\flux\ComfyUI_windows_portable\ComfyUI\comfy\controlnet.py", line 238, in get_control
    control = self.control_model(x=x_noisy.to(dtype), hint=self.cond_hint, timesteps=timestep.to(dtype), context=context.to(dtype), **extra)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\flux\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\flux\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\flux\ComfyUI_windows_portable\ComfyUI\comfy\ldm\flux\controlnet_xlabs.py", line 104, in forward
    return self.forward_orig(img, img_ids, hint, context, txt_ids, timesteps, y, guidance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\flux\ComfyUI_windows_portable\ComfyUI\comfy\ldm\flux\controlnet_xlabs.py", line 62, in forward_orig
    controlnet_cond = rearrange(controlnet_cond, "b c (h ph) (w pw) -> b (h w) (c ph pw)", ph=2, pw=2)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\flux\ComfyUI_windows_portable\python_embeded\Lib\site-packages\einops\einops.py", line 591, in rearrange
    return reduce(tensor, pattern, reduction="rearrange", **axes_lengths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\flux\ComfyUI_windows_portable\python_embeded\Lib\site-packages\einops\einops.py", line 533, in reduce
    raise EinopsError(message + "\n {}".format(e))

**Comment by kaykay-drills** [comment]
> I have error: Error occurred when executing `SamplerCustomAdvanced`

Please refer to this comment, it solved my issue.

> Had the same problem, with XLabs Flux_dev_fp8. Try this model instead https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors

**Comment by heinrichI** [comment]
> > I have error: Error occurred when executing `SamplerCustomAdvanced`
> 
> Please refer to this comment, it solved my issue.
> 
> > Had the same problem, with XLabs Flux_dev_fp8. Try this model instead https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors

Not help:
image

**Comment by ZiBrianQian** [comment]
> > > I have error: Error occurred when executing `SamplerCustomAdvanced`
> > 
> > 
> > Please refer to this comment, it solved my issue.
> > > Had the same problem, with XLabs Flux_dev_fp8. Try this model instead https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors
> 
> Not help: image

Can you send workflow here? I'll check

**Comment by KINGLIFER** [comment]
any luck with these errors? I get 'NoneType' object has no attribute 'keys' for one and 'pos_embed.proj.weight' (fluex.1-dev) for the other.

**Comment by KINGLIFER** [comment]
> > > git checkout xlabs_flux_controlnet
> > 
> > 
> > yes, first thing I did was to checkout this branch :) still doesn't work :(
> > ```
> > F:\Projects\AI\COMFY-UI\ComfyUI_windows_portable\ComfyUI\ComfyUI>git branch
> > * xlabs_flux_controlnet
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > !!! Exception during processing!!! 'NoneType' object has no attribute 'keys'
> > ```
> 
> Update ComfyUI. then run the git checkout xlabs_flux_controlnet again. It worked for m.

what do you mean run the git... https://github.com/XLabs-AI/x-flux.git or you mean just run the controlnet again. Just want to be sure. if I do the git do I do it in the custom nodes folder?

**Comment by kaykay-drills** [comment]
> any luck with these errors? I get 'NoneType' object has no attribute 'keys' for one and 'pos_embed.proj.weight' (fluex.1-dev) for the other.

`pos_embed.proj.weight` meaning you are using the other control net, please don't, it is not supported yet

regarding the one involving the `NoneType`  `keys`
I created a public workflow on Civitai with a detailed guide

 https://civitai.com/models/634368/img2img-flux1-dev-fp8-cnet-canny

**Comment by Ling-APE** [comment]
Hi, I have been fiddling around with the ControlNet and really struggling to reproduce the same output quality as the demo they have on the HF/GitHub page and I have come to the conclusion that the original output demo may not be the initial 1st pass generation with the ControlNet, there may be some upscaling/detailing involved to archive the quality they demonstrate. Here is an example I made:

The exact reference photo from their page:
image

The initial generation with control net:
image

You can see the line artifacts mentioned by @kaykay-drills but my generation seems to have even worse quality, I can see @kaykay-drills archive far better quality even with the first pass by looking at the workflow image you provided, I tried to copy your setting but have no luck reproducing the same result, maybe I am setting something wrong here, would you mind sharing the image you generated for us to reference?

upscaling with tiled diffusion and color match to original:
image

it would great if someone can share their setting to get this to work right out of the sampler without any post processing,

**Comment by kaykay-drills** [comment]
> You can see the line artifacts mentioned by @kaykay-drills but my generation seems to have even worse quality, I can see @kaykay-drills archive far better quality even with the first pass by looking at the workflow image you provided, I tried to copy your setting but have no luck reproducing the same result, maybe I am setting something wrong here, would you mind sharing the image you generated for us to reference?
> 
> it would great if someone can share their setting to get this to work right out of the sampler without any post processing.\

there's no magic number. I tried out a few renders by changing numbers by multiple of 5 (what I usually do) or simply +1 or -1, depending on the value.

Important to mention I use an upscale in my workflow. it is called `hiresfixscale` node.

This is the URL to my workflow in case you want to try it out.
https://civitai.com/models/634368/img2img-flux1-dev-fp8-cnet-canny

**Comment by ZiBrianQian** [comment]
> > > > git checkout xlabs_flux_controlnet
> > > 
> > > 
> > > yes, first thing I did was to checkout this branch :) still doesn't work :(
> > > ```
> > > F:\Projects\AI\COMFY-UI\ComfyUI_windows_portable\ComfyUI\ComfyUI>git branch
> > > * xlabs_flux_controlnet
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > !!! Exception during processing!!! 'NoneType' object has no attribute 'keys'
> > > ```
> > 
> > 
> > Update ComfyUI. then run the git checkout xlabs_flux_controlnet again. It worked for m.
> 
> what do you mean run the git... https://github.com/XLabs-AI/x-flux.git or you mean just run the controlnet again. Just want to be sure. if I do the git do I do it in the custom nodes folder?

Go to your ComfyUI folder (in my case D:\AI\ComfyUI\ComfyUI) and run CMD, there run `git checkout xlabs_flux_controlnet`

**Comment by Omarsmsm** [comment]
> > > > > git checkout xlabs_flux_controlnet
> > > > 
> > > > 
> > > > yes, first thing I did was to checkout this branch :) still doesn't work :(
> > > > ```
> > > > F:\Projects\AI\COMFY-UI\ComfyUI_windows_portable\ComfyUI\ComfyUI>git branch
> > > > * xlabs_flux_controlnet
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ```
> > > > !!! Exception during processing!!! 'NoneType' object has no attribute 'keys'
> > > > ```
> > > 
> > > 
> > > Update ComfyUI. then run the git checkout xlabs_flux_controlnet again. It worked for m.
> > 
> > 
> > what do you mean run the git... https://github.com/XLabs-AI/x-flux.git or you mean just run the controlnet again. Just want to be sure. if I do the git do I do it in the custom nodes folder?
> 
> Go to your ComfyUI folder (in my case D:\AI\ComfyUI\ComfyUI) and run CMD, there run `git checkout xlabs_flux_controlnet`

would one have to switch back to the main branch once it works?

**Comment by ZiBrianQian** [comment]
> > > > > > git checkout xlabs_flux_controlnet
> > > > > 
> > > > > 
> > > > > yes, first thing I did was to checkout this branch :) still doesn't work :(
> > > > > ```
> > > > > F:\Projects\AI\COMFY-UI\ComfyUI_windows_portable\ComfyUI\ComfyUI>git branch
> > > > > * xlabs_flux_controlnet
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > ```
> > > > > !!! Exception during processing!!! 'NoneType' object has no attribute 'keys'
> > > > > ```
> > > > 
> > > > 
> > > > Update ComfyUI. then run the git checkout xlabs_flux_controlnet again. It worked for m.
> > > 
> > > 
> > > what do you mean run the git... https://github.com/XLabs-AI/x-flux.git or you mean just run the controlnet again. Just want to be sure. if I do the git do I do it in the custom nodes folder?
> > 
> > 
> > Go to your ComfyUI folder (in my case D:\AI\ComfyUI\ComfyUI) and run CMD, there run `git checkout xlabs_flux_controlnet`
> 
> would one have to switch back to the main branch once it works?

Don't think so. Everything works for me just fine

**Comment by KINGLIFER** [comment]
> git checkout xlabs_flux_controlnet

did that it worked... updated comfyui and now it makes the error again. a new error. I will google to see why. 
MMDiT.__init__() got an unexpected keyword argument 'image_model'

**Comment by ZiBrianQian** [comment]
> > git checkout xlabs_flux_controlnet
> 
> did that it worked... updated comfyui and now it makes the error again. a new error. I will google to see why. MMDiT.**init**() got an unexpected keyword argument 'image_model'

Try this model instead https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors

**Comment by JorgeR81** [comment]
This also works for the new Xlabs's Depth and HED ControlNets.
https://huggingface.co/XLabs-AI/flux-controlnet-collections
