### ISSUE TITLE
Performance Regression & OOM in v0.6.0 compared to v0.5.1 (RTX 4080)

### ISSUE THREAD

**Issue by Mr-small-2-six** [comfyanonymous/ComfyUI#11533]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

Describe the bug
I am experiencing significant performance degradation and Out of Memory (OOM) issues after updating from v0.5.1 to v0.6.0. With the exact same workflow and settings, the behavior has changed drastically.
Comparison:
v0.5.1: Stable, no OOM. Performance was acceptable (approx. 700s for 10 images, ~70s/img).
v0.6.0: Frequent OOM. Even when it runs, it is much slower (approx. 400s for only 2 images, ~200s/img).
Environment:
GPU: NVIDIA RTX 4080 (16GB VRAM)
RAM: 128GB
Model: QwenEdit 2511 BF16
Weight Type: Loaded using fp8_e4m3 (f8_em4)
Workflow: Identical across both versions.
Additional Context:
I also noticed the following warning in the console which might be related to node logic or memory management:
WARNING: ProcessString.IS_CHANGED() got an unexpected keyword argument 'input_string'

### Actual Behavior

After upgrading from v0.5.1 to v0.6.0, I encountered a significant performance regression and frequent Out of Memory (OOM) issues using the same workflow and hardware (RTX 4080 16GB, 128GB RAM).
Comparison:
v0.5.1: Stable and efficient. 10 images were completed in about 700 seconds (~70s/img).
v0.6.0: Frequent OOM errors. When it does run, it is extremely slow, taking 400 seconds for just 2 images (~200s/img).
Technical Details:
Model: QwenEdit 2511 BF16
Weight type: fp8_e4m3
Console Warning: WARNING: ProcessString.IS_CHANGED() got an unexpected keyword argument 'input_string'
It seems like memory management or VRAM offloading logic has changed significantly in the new version, leading to much higher resource consumption.

### Steps to Reproduce

Update the environment to version 0.6.0.
Load a workflow using the QwenEdit 2511 BF16 model.
Set the model weight type to fp8_e4m3.
Run a batch generation (e.g., 2 or more images).
Monitor VRAM usage and generation time. Compare the results with version 0.5.1.
Check the console for the ProcessString.IS_CHANGED warning and observe the OOM crash during the sampling process.

### Debug Logs

```powershell
WARNING: ProcessString.IS_CHANGED() got an unexpected keyword argument 'input_string'
HTTP Request: POST https:///v1/chat/completions "HTTP/1.1 200 OK"
Requested to load WanVAE
Unloaded partially: 621.46 MB freed, 10947.53 MB remains loaded, 252.01 MB buffer reserved, lowvram patches: 596
loaded completely; 291.73 MB usable, 242.03 MB loaded, full load: True
Requested to load QwenImageTEModel_
Unloaded partially: 6626.12 MB freed, 4321.41 MB remains loaded, 378.09 MB buffer reserved, lowvram patches: 760
loaded completely; 8875.12 MB usable, 7910.29 MB loaded, full load: True
Unloaded partially: 1674.54 MB freed, 2646.86 MB remains loaded, 378.09 MB buffer reserved, lowvram patches: 791
loaded partially; 11821.09 MB usable, 11568.99 MB loaded, 7914.96 MB offloaded, 252.01 MB buffer reserved, lowvram patches: 0
100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [03:39<00:00, 27.47s/it]
loaded partially; 11821.09 MB usable, 11568.99 MB loaded, 7914.96 MB offloaded, 252.01 MB buffer reserved, lowvram patches: 0
 12%|██████████▍                                                                        | 1/8 [02:19<16:19, 139.95s/it]
```

**Comment by comfyanonymous** [comment]
I don't see any difference in memory usage between v0.5.1 and v0.6.0 which is normal because none of the code related to model loading/memory changed between these versions.

**Comment by Mr-small-2-six** [comment]
> I don't see any difference in memory usage between v0.5.1 and v0.6.0 which is normal because none of the code related to model loading/memory changed between these versions.

It’s possible that updating all the custom nodes messed up some dependencies. Even though I'm using the exact same workflow, this issue still persists. I’ll try a fresh install to see if that fixes it."

**Comment by rattus128** [comment]
I also tried the QWEN image edit template between 0.5.1 and 0.6.0 and get the same VRAM usage to with 1MB margin. RTX5090 linux.

**Comment by document10** [comment]
Can confirm I'm experiencing similar issues. I'm using an 8GB RTX 4060 (Laptop). Using SDXL I used to generate images in ~35s, now it takes ~52s.

**Comment by zwukong** [comment]
they are using 4090 or 5090 to dev, ignoring all the performance issues.--disable-pinned-memory  --disable-async-offload  may help.  i have tested many params, still need to ajust reserve-vram in different models, or comfyui will try to eat all your vram and stuck

**Comment by document10** [comment]
>It’s possible that updating all the custom nodes messed up some dependencies. 

You may be onto something. I've updated ComfyUI once again and the performance regression is gone. So `v0.7.0` probably fixed those issues and is worth giving a shot.

**Comment by J-Cott** [comment]
> I don't see any difference in memory usage between v0.5.1 and v0.6.0 which is normal because none of the code related to model loading/memory changed between these versions.

I used to be able to merge two bf16 Qwen models on 24GB of Vram and 64GB of RAM, if I closed down all other programs (last time I tried was the end of November 2025),  but now I always get an OOM error.

**Comment by rattus128** [comment]
> > I don't see any difference in memory usage between v0.5.1 and v0.6.0 which is normal because none of the code related to model loading/memory changed between these versions.
> 
> I used to be able to merge two bf16 Qwen models on 24GB of Vram and 64GB of RAM, if I closed down all other programs (last time I tried was the end of November 2025), but now I always get an OOM error.

VRAM OOM or regular OOM? Can I get the backtrace of your oom and workflow? This is probably different to OP.

**Comment by KLL535** [comment]
Could you tell me what code I can use to clear the model from RAM? This code doesn't work:
```
        print("Unload Model:")
        print(" - Unloading all models...")
        model_management.unload_all_models()
        model_management.soft_empty_cache(True)
        try:
            print(" - Clearing Cache...")
            gc.collect()
            torch.cuda.empty_cache()
            torch.cuda.ipc_collect()
        except:
            print("   - Unable to clear cache")
        return (kwargs.get("value"),)
```

I can't run two large models at the same time. If I run them in separate workflow, everything works. But if I combine them into a single workflow (MODEL 1 -> MODEL 2), they start loading simultaneously, the RAM memory isn't cleared after MODEL 1, and everything freezes. 64 GB of RAM isn't enough.

**Comment by XieJunchen** [comment]
I also agree with the view that "compared to v0.5.1, v0.6.0 has performance degradation and memory overflow issues." Currently, the system frequently crashes and restarts after OOM, which is likely a new bug introduced during version iteration

**Comment by zipac2** [comment]
I have been dealing with the same issue as @KLL535.
Video generation becomes unstable for me as soon as it switches from the "High model" to the "Low model." I experienced this issue before when updating ComfyUI to v0.6, and it seemed to be resolved with a fresh install. However, now both v0.7 and v0.6 no longer work, even after fresh installs, with the same problem persisting.
It’s like the RAM from the High model isn’t being cleared before switching to the Low model. 
Since it completely freezes the system, I’ve had to hard reset the PC multiple times while trying to fix the issue, which has made me worry about potentially damaging it.

**Comment by J-Cott** [comment]
> > > I don't see any difference in memory usage between v0.5.1 and v0.6.0 which is normal because none of the code related to model loading/memory changed between these versions.
> > 
> > 
> > I used to be able to merge two bf16 Qwen models on 24GB of Vram and 64GB of RAM, if I closed down all other programs (last time I tried was the end of November 2025), but now I always get an OOM error.
> 
> VRAM OOM or regular OOM? Can I get the backtrace of your oom and workflow? This is probably different to OP.

Sorry it took so long to get back, it is a Memory OOM (even on the latest version today)

Here is the error:

Requested to load QwenImage
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "C:\ComfyUI_For_Wan\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI\execution.py", line 518, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_For_Wan\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI\execution.py", line 329, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_For_Wan\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI\custom_nodes\comfyui-lora-manager\py\metadata_collector\metadata_hook.py", line 165, in async_map_node_over_list_with_metadata
    results = await original_map_node_over_list(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_For_Wan\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI\execution.py", line 303, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\ComfyUI_For_Wan\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI\execution.py", line 291, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\ComfyUI_For_Wan\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI\comfy_extras\nodes_model_merging.py", line 355, in save
    save_checkpoint(model, filename_prefix=filename_prefix, output_dir=self.output_dir, prompt=prompt, extra_pnginfo=extra_pnginfo)
  File "C:\ComfyUI_For_Wan\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI\comfy_extras\nodes_model_merging.py", line 225, in save_checkpoint
    comfy.sd.save_checkpoint(output_checkpoint, model, clip, vae, clip_vision, metadata=metadata, extra_keys=extra_keys)
  File "C:\ComfyUI_For_Wan\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI\comfy\sd.py", line 1578, in save_checkpoint
    model_management.load_models_gpu(load_models, force_patch_weights=True)
  File "C:\ComfyUI_For_Wan\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI\comfy\model_management.py", line 715, in load_models_gpu
    loaded_model.model_load(lowvram_model_memory, force_patch_weights=force_patch_weights)
  File "C:\ComfyUI_For_Wan\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI\comfy\model_management.py", line 520, in model_load
    self.model_use_more_vram(use_more_vram, force_patch_weights=force_patch_weights)
  File "C:\ComfyUI_For_Wan\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI\comfy\model_management.py", line 550, in model_use_more_vram
    return self.model.partially_load(self.device, extra_memory, force_patch_weights=force_patch_weights)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_For_Wan\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI\comfy\model_patcher.py", line 983, in partially_load
    raise e
  File "C:\ComfyUI_For_Wan\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI\comfy\model_patcher.py", line 980, in partially_load
    self.load(device_to, lowvram_model_memory=current_used + extra_memory, force_patch_weights=force_patch_weights, full_load=full_load)
  File "C:\ComfyUI_For_Wan\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI\comfy\model_patcher.py", line 778, in load
    self.patch_weight_to_device(key, device_to=device_to)
  File "C:\ComfyUI_For_Wan\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI\comfy\model_patcher.py", line 632, in patch_weight_to_device
    out_weight = comfy.lora.calculate_weight(self.patches[key], temp_weight, key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_For_Wan\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI-Easy-Install\ComfyUI\comfy\lora.py", line 419, in calculate_weight
    weight += function(strength * comfy.model_management.cast_to_device(diff, weight.device, weight.dtype))
                       ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
torch.OutOfMemoryError: Allocation on device

Memory summary: |===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      | 221184 KiB |  19446 MiB |      0 B   |      0 B   |
|       from large pool |      0 KiB |      0 MiB |      0 B   |      0 B   |
|       from small pool |      0 KiB |      0 MiB |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| Active memory         | 221184 KiB |  19446 MiB |      0 B   |      0 B   |
|       from large pool |      0 KiB |      0 MiB |      0 B   |      0 B   |
|       from small pool |      0 KiB |      0 MiB |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| Requested memory      |      0 B   |      0 B   |      0 B   |      0 B   |
|       from large pool |      0 B   |      0 B   |      0 B   |      0 B   |
|       from small pool |      0 B   |      0 B   |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| GPU reserved memory   |  23776 MiB |  23840 MiB |      0 B   |      0 B   |
|       from large pool |      0 MiB |      0 MiB |      0 B   |      0 B   |
|       from small pool |      0 MiB |      0 MiB |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| Non-releasable memory |      0 B   |      0 B   |      0 B   |      0 B   |
|       from large pool |      0 B   |      0 B   |      0 B   |      0 B   |
|       from small pool |      0 B   |      0 B   |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| Allocations           |       0    |       0    |       0    |       0    |
|       from large pool |       0    |       0    |       0    |       0    |
|       from small pool |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Active allocs         |       0    |       0    |       0    |       0    |
|       from large pool |       0    |       0    |       0    |       0    |
|       from small pool |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| GPU reserved segments |       0    |       0    |       0    |       0    |
|       from large pool |       0    |       0    |       0    |       0    |
|       from small pool |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |       0    |       0    |       0    |       0    |
|       from large pool |       0    |       0    |       0    |       0    |
|       from small pool |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize allocations  |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize GPU segments |       0    |       0    |       0    |       0    |
|===========================================================================|

Got an OOM, unloading all loaded models.
Prompt executed in 00:20:11

Basic Workflow attached.

[Jib Mix Qwen V6_ merge_Test.json](https://github.com/user-attachments/files/24587595/Jib.Mix.Qwen.V6_.merge_Test.json)

I guess In the mean time I will have to rent a cloud RTX 6000 Pro to do my QWEN merges.
